### ISSUE TITLE
Presentation Revision

### ISSUE THREAD

**Issue by begununal** [bounswe/bounswe2017group9#104]
We decided that slides need some changes. 
@hilaldonmez , @ozturkihsan , @necipfazilergun had a meeting to rearrange the slides. 
@ozturkihsan was assigned to rewrite the slides on latex.

**Comment by ozturkihsan** [comment]
We have revised the presentation slides and put the last touches with @begununal ,@necipfazilergun , @hilaldonmez

**Comment by ffguven** [comment]
Done.
