### ISSUE TITLE
Web services do not work properly 

### ISSUE THREAD

**Issue by abtasdan** [bounswe/bounswe2017group9#106]

**Comment by hilaldonmez** [comment]
I wrote the document of Web Service. If the error is about /concert path which is a POST for  createConcert, ,  this path should be /concerts. This is my mistake in the document.

**Comment by ffguven** [comment]
Because the service is under test and development i had not deployed it to Amazon AWS. Now it is active on [this url](http://concerterservice-env.yzkzigt6vn.eu-central-1.elasticbeanstalk.com/).
