### ISSUE TITLE
Revision of Project Plan

### ISSUE THREAD

**Issue by hilaldonmez** [bounswe/bounswe2017group9#112]
I have just revised [Milestones documentation](https://docs.google.com/spreadsheets/d/1AFgT8MDmsyWtZ1xJioQdQlPus_uPgPQOrfUq67Adj0E/edit#gid=0). Also, I have to revise the Gantt Chart. My deadline is 5/11/2017 at 23:59.

**Comment by hilaldonmez** [comment]
I have to revise Milestones documentation after each customer feedback.  Last revision deadline is on  21/11/2017 at 23:59. After I update this documentation , @ozturkihsan  will revise the Gantt Chart.  His deadline is on 22/11/2017 at 23:59.

**Comment by hilaldonmez** [comment]
We have just worked on Milestones planning. After I write milestones documentation , @ozturkihsan  will update the gantt chart. Please check the milestone documentation and gantt chart until 23.11.2017 at 12:00.

**Comment by ozturkihsan** [comment]
Gant Chart is reviewed and the link is updated.
