### ISSUE TITLE
Milestone Report-1

### ISSUE THREAD

**Issue by thedorum** [bounswe/bounswe2017group9#113]
I uploaded the Milestone Report-1 here, I will add it to our wiki-page after the last touchs by @ffguven 

[MilestoneReport-1.docx](https://github.com/bounswe/bounswe2017group9/files/1440823/MilestoneReport-1.docx)

**Comment by hilaldonmez** [comment]
Also, I put this report into Milestone section in our Wiki page.

**Comment by thedorum** [comment]
Above .docx file is not opening , so i am uploading the pdf version of it. 
[MilestoneReport-1.pdf](https://github.com/bounswe/bounswe2017group9/files/1440868/MilestoneReport-1.pdf)

**Comment by thedorum** [comment]
@ffguven made some changes. Milestone Report-1 is ready now! 
[MilestoneReport-1.pdf](https://github.com/bounswe/bounswe2017group9/files/1441034/MilestoneReport-1.pdf)

**Comment by thedorum** [comment]
@hilaldonmez is going to edit the wiki Milestone1 page. 
https://drive.google.com/file/d/0B3LgbKPcnZw-UmhYZUd6Zm5ILTQ/view?usp=sharing

**Comment by hilaldonmez** [comment]
I have just edited the Wiki page.

**Comment by ffguven** [comment]
Done.
