### ISSUE TITLE
Notes From Milestone Presentation

### ISSUE THREAD

**Issue by ghost** [bounswe/bounswe2017group9#115]
**Remarks**
- Instagram/Flickr can be used for storing images.

**About next milestone**
- Login/Sign-up features will be implemented.
- Attending/Maybe etc choices will be implemented.
- Recommendations and usage of Semantic Tags.
- Main page design will be similar to Facebook main page.
- Android and Web will have same functionalities.
- Spotify integration.

**Advices as extra**
- The place that sells tickets can be mentioned in concert page.
- Recommendations considering only last week's info.
- Classifying comments.
- Visit YouTube concert videos and read comments for new ideas.

**Comment by ffguven** [comment]
Considered.
