### ISSUE TITLE
upgrade service document

### ISSUE THREAD

**Issue by abtasdan** [bounswe/bounswe2017group9#141]
Service document is old.

**Comment by hilaldonmez** [comment]
I have just worked on this documentation. I set the deadline on 24/11/2017 at 13:00.

**Comment by hilaldonmez** [comment]
I have just updated [this api document](https://swaggerhub.com/apis/Concerter/Concerter/1.0.0). As long as there are changes in api, I will try to update this document.

**Comment by ffguven** [comment]
Updated. May be revised later.
