### ISSUE TITLE
Functional - User Requirements

### ISSUE THREAD

**Issue by aticie** [bounswe/bounswe2017group9#15]
As the result of our second meeting, 3 people including me, are assigned for editing the wiki page for Functional-User Requirements. 

Deadline: 20.02.2017 midnight

**Comment by aticie** [comment]
I changed all the sentences in user requirements, according to lecture notes. Please check if I missed anything. Also, I added references at the bottom of the page, where you can check if I have placed any requirements mistakenly.

**Comment by hilaldonmez** [comment]
I have modified on Functional-User Requirement. If some changes are necessary, you can edit this issue on Wiki.

**Comment by ghost** [comment]
I have done a review of this part. Nicely done 👍
