### ISSUE TITLE
Functional System Requirements

### ISSUE THREAD

**Issue by ghost** [bounswe/bounswe2017group9#18]
After our second meeting I, Akif and Fatih were assigned to prepare Functional System Requirements part of  Requirements wiki page.
  
Deadline: 20.02.2017 / 23.59

**Comment by ghost** [comment]
I have done my part of the work. Waiting for reviews and revisions (on whatsapp) :)

**Comment by ffguven** [comment]
I have offered integrating users' other social media accounts such as Facebook,Twitter,Google+ into our application by using "Sign up with Facebook" etc. And the proposal is accepted by every group member. Then, i added this proposal to requirements page as "desirable" requirement.

**Comment by mehmetakify** [comment]
I have finished the all review and advising yesterday, I also finished my part.

**Comment by ghost** [comment]
I have revised all the recomendations and warnings that our TA has mentioned via piazza.
One by one, all the concerns were fulfilled.
