### ISSUE TITLE
Gathering Mockup Tool Recommendations

### ISSUE THREAD

**Issue by aticie** [bounswe/bounswe2017group9#20]
We can gather the recommendations for mockup tools we want to use under this issue. I have found that most of the mockup tools on the internet requires payment for their product. The only free product I could find is https://www.invisionapp.com. Please check it out and if you have other recommendations, write as comment.

**Comment by ffguven** [comment]
I found concept.ly as a different mockup tool, it is also reasonable but there is a constraint which is the mockup tool is free for only 2 projects. In this case, i think Invision App is the best choice for us.

**Comment by ffguven** [comment]
The sub-team that is responsible for creating Mobile Mockups will use Android Studio and Invision App.
Another team that is responsible for creating Web Mockups will use Ninja Mock to create Web Mockups.
