### ISSUE TITLE
Creating Mobile Mockups

### ISSUE THREAD

**Issue by ffguven** [bounswe/bounswe2017group9#22]
We have been divided into two groups in creating mockups for application. The assignees of this issue will deal with creating Mobile Mockups.

We have decided to use Android Studio's XML design property to create some screen designs, and then Invison App in order to create some use-cases for application.

**Comment by ffguven** [comment]
I will create mockups for user's profile page and concert page. Also, i am going to design a sub-menu bar to use it anywhere in mobile application.

**Comment by hilaldonmez** [comment]
I will generate mockups for  unregistered user activity page and main page .

**Comment by ffguven** [comment]
Mobile mockups are done!

**Comment by ffguven** [comment]
Mobile mockups are done!
