### ISSUE TITLE
Creating Web Mockups

### ISSUE THREAD

**Issue by begununal** [bounswe/bounswe2017group9#23]
We have been divided into two groups in creating mockups for application. The assignees of this issue will deal with creating Web Mockups.

We searched some mockup tools and decided to use Ninja Mock. We created scenarios in order to discuss what the application allow to do. We have decided the content of the pages and designs of them.

**Comment by kahremane** [comment]
We shared web mockups accordingly;

- [x] -Login Activity (BEGÜN ÜNAL)
- [x] -Signup Activity (BEGÜN ÜNAL)
- [x] -Profile Page(EFEHAN ATICI)
- [x] -Non-Registered User Welcome Page (EMRE KAHREMAN)
- [x] -Homepage (EMRE KAHREMAN)
- [x] -Explore (İHSAN ÖZTÜRK)
- [x] -Notifications(İHSAN ÖZTÜRK)
- [x] -Concert Page(NECİP FAZIL ERGÜN)


For any help/support issues we will use whatsapp.

**Comment by aticie** [comment]
As we discussed in the last meeting, we have to reconstruct our mock-ups. So, I'm assigning everyone the same mock-up pages:

- [x] -Login Activity (BEGÜN ÜNAL)
- [x] -Signup Activity (BEGÜN ÜNAL)
- [x] -Profile Page(EFEHAN ATICI)
- [x] -Non-Registered User Welcome Page (EMRE KAHREMAN)
- [x] -Homepage (EMRE KAHREMAN)
- [x] -Explore (İHSAN ÖZTÜRK)
- [x] -Notifications(İHSAN ÖZTÜRK)
- [x] -Concert Page(NECİP FAZIL ERGÜN)
- [x] -Concert Creation Page(NECİP FAZIL ERGÜN)

Please upload the mock-up file in the "Web Mock-ups" folder on the main page.
