### ISSUE TITLE
Working on Project Plan Revision

### ISSUE THREAD

**Issue by hilaldonmez** [bounswe/bounswe2017group9#256]
There were some changes before final demo. I have just added into [project plan document](https://docs.google.com/spreadsheets/d/1AFgT8MDmsyWtZ1xJioQdQlPus_uPgPQOrfUq67Adj0E/edit#gid=0) . @ozturkihsan will change the gant chart according this documentation. 
- Deadline : 30/12/2017 20:00 .

**Comment by ozturkihsan** [comment]
Gant chart is updated. It can be seen on Project Plan page at Wiki.
