### ISSUE TITLE
Revising Mobile Mockups

### ISSUE THREAD

**Issue by ffguven** [bounswe/bounswe2017group9#27]
Mobile and Web Mockups were negotiated in Meeting 4 and the group has taken some decisions about mockups with regarding to Can Tunca's suggestions.

There are 3 things in Mobile Mockup's to-do list.

1) Simulating the scroll down property of mobile devices by preparing new pages for scrolled down pages and relate them to each other. (Second image is scrolled down version of first image etc.)

2) Adding missed pages such as "add concert page" and  "explore page".

3) Integration with web mockups will be created by revising some of the existing pages. 
   * Signup and login page fields will be common to each mockups.
   * Filtering concerts will have common fields with web mockups.

**Comment by hilaldonmez** [comment]
* I will arrange sign up page , login page , home page and unregistered page .  
* I and Fatih will generate a scenario for the mobile mockups.
* The deadline of all of them  is 4 March midnight.

**Comment by ffguven** [comment]
Mobile Mockups have been revised.
