### ISSUE TITLE
Determining use cases and drawing use case diagram [Assignment 5]

### ISSUE THREAD

**Issue by ffguven** [bounswe/bounswe2017group9#28]
In Meeting 4, the group has divided assignment 5's work into team members. And here are the use cases and work sharing.

Use cases :
- [x] - Sign up and login cases -> @begununal 
- [x] - Forgot password and search -> @ozturkihsan 
- [x] - Edit profile and create concerts -> @aticie 
- [x] - Edit and delete concerts -> @necipfazilergun 
- [x] - Create,edit and delete comments -> @kahremane 
- [x] - Sorting comments and up/down vote for comments -> @mehmetakify 
- [x] - Follow user and concert info flagging -> @kasimbozdag 

Deadline for preparing use cases is **03/04/2017 17:00**
Use case diagram:
@dogacandorum will gather whole cases and draw the diagram.

Deadline for drawing use case diagram is **03/06/2017 midnight**

Determined cases are not sharp, there might be some additional cases or changes on that issue. If there will be additional use cases, @ffguven and @hilaldonmez will deal with them.

**Comment by ffguven** [comment]
Use case `#18 View Concert Page` is added to related page.

**Comment by ffguven** [comment]
All use cases can be seen on [that page](https://github.com/bounswe/bounswe2017group9/wiki/Use-Cases).

**Comment by dogacandorum** [comment]
I draw the use case diagram, uploaded the system and created the wiki page.
