### ISSUE TITLE
Getting feedback on scenario

### ISSUE THREAD

**Issue by aticie** [bounswe/bounswe2017group9#29]
We have created a scenario but we need the feedback from our customers.

**Comment by kahremane** [comment]
We have no feedback now.
When feedback comes, I will work on the scenerio (if necessary)

**Comment by aticie** [comment]
We have feedback from our customers stating that:

First of all, what we really wanted you to do was to incorporate the scenarios in your use case steps. So each use case would have a little scenario with real people and example usages. Note that this is different from the assignment we gave in the earlier semesters. But, please do not change your use cases at this point, it is OK. What I recommend you to do is to create a separate page for scenarios and have AT LEAST two scenarios. The one above is OK with only one problem: You need to enumerate the steps in the scenario to increase the readability. You should add another scenario like this one (you may want to divide this into two scenarios, or come up with another one). The second scenario may have some shared features with the first scenario, that's OK. The second scenario additionally may include some important features such as advanced search and recommendations, which are lacking in your first scenario. For instance, you may make the user attend several concerts and then you may come up with a few recommended concerts and explain why they are recommended. Location is also another important feature. You may want to use advanced search to filter concerts in a specific district.
 
In a couple of days, I will give you detailed feedback on your use cases and use case diagram. Your mockups are nicely done.

**Comment by kahremane** [comment]
We get feedback, so we can close this issue.
