### ISSUE TITLE
Adding "Get Recommendations" Use Case

### ISSUE THREAD

**Issue by ffguven** [bounswe/bounswe2017group9#49]
Get Recommendations Use Case will be added to Use Cases' wiki page until 04/11/2017 23:59

**Comment by aticie** [comment]
I've handled this issue (loosely). Please review.

Also, I couldn't think of any postconditions for getting recommendations ? Any idea would be helpful.

**Comment by ffguven** [comment]
One of the postconditions could be "Registered user might decide to attend one of the recommended concerts".

**Comment by aticie** [comment]
Issue is resolved.
