### ISSUE TITLE
API Research Assignments

### ISSUE THREAD

**Issue by aticie** [bounswe/bounswe2017group9#5]
We have selected the API as Microsoft Vision API. The research needed for each individual is as follows:

analyze image -> fatih
describe image -> emre kahreman
get thumbnail -> hilal dönmez
list domain specific models -> ihsan
ocr -> begün ünal
recognize domain specific content -> doğa
tag image -> necip

**Comment by kahremane** [comment]
describe image is done

**Comment by ghost** [comment]
Tag Image is complete :)

**Comment by dogacandorum** [comment]
recognize domain specific content research is  done. :=)

**Comment by ffguven** [comment]
API Research assignment was finished on time.
