### ISSUE TITLE
Creating a working API

### ISSUE THREAD

**Issue by aticie** [bounswe/bounswe2017group9#56]
Our last assignment is to create an API for our project. We decided that our API should have functions that our project benefits from. So, according to this, we have assigned people for some tasks in the last meeting.

[You can access the meeting notes about the API from here.](https://github.com/bounswe/bounswe2017group9/wiki/Meeting-Note8)

The deadline is for 24.04.2017, 23:59 (Tonight).

Extended deadline is for 29.04.2017, 23:59 (Sunday night), if you can't manage to submit your part in time.

**Comment by ffguven** [comment]
Some of the team members wrote their related functions and a working API is created partly.
