### ISSUE TITLE
Deciding Test Cases

### ISSUE THREAD

**Issue by begununal** [bounswe/bounswe2017group9#59]
We have decided the test case topics and distributed them to the group members. All members will write related and required test cases of that topics.

**Comment by kahremane** [comment]
Members who are responsible for the test parts are announced on the "Meeting 9" page. Each member can see related part and work on it. 

I think my part of the cases (getting notificationg-following user)  is done. If any mistake seen on that please remind me.

**Comment by aticie** [comment]
Also since it isn't stated here deadlines are: 08.05.2017 – 23:59

**Comment by ghost** [comment]
I have updated Requirements 1.2.1.3 and 1.2.1.4 because they were out-dated in terms of method of dealing with their tasks.

**Comment by ghost** [comment]
I have done my part. Please revise (if you want).

**Comment by ozturkihsan** [comment]
I have finished getting recommendation and sign-up/login with social media account test cases. You can revise them.

**Comment by ffguven** [comment]
Test cases were done.
