### ISSUE TITLE
Unit tests for API Project 

### ISSUE THREAD

**Issue by ozturkihsan** [bounswe/bounswe2017group9#60]
We have distributed the Unit Test task for our API to the group members below. These members will write required test cases by using Junit.

@ffguven  
@hilaldonmez 
@aticie 
@begununal

**Comment by hilaldonmez** [comment]
I will create two test functions for login and signUp functions by using JUnit until 8 May 23.59 .

**Comment by ffguven** [comment]
Unit tests were written.
