### ISSUE TITLE
Updating Project Plan

### ISSUE THREAD

**Issue by kahremane** [bounswe/bounswe2017group9#71]
Our project plan's dates changed a little. I will edit some parts of it with @hilaldonmez

**Comment by hilaldonmez** [comment]
I have just updated the project plan. The newest version of the project plan is at Wiki page.

**Comment by kahremane** [comment]
We revised the dates of our plan. According to our new members and their roles we arranged and added deadlines of each responsibility. (see the following link)

https://github.com/bounswe/bounswe2017group9/wiki/Milestone-%231

**Comment by aticie** [comment]
Keep up the good work guys 💪

Also there's still an open issue from 6 months ago btw, don't forget to close it :P
