### ISSUE TITLE
Generating some Web BackEnd functions

### ISSUE THREAD

**Issue by hilaldonmez** [bounswe/bounswe2017group9#93]
I have just implemented the Web Back End part. I have generated some functions. However, API is not ready to use exactly, some of them were not implemented.  After API is ready, they will be implemented. This part is located at hilaldonmez-BackEndExamples branch and is called as Concerter.  On the other hand, API connection was achieved in this code.  These are the functions which I have initialized:
* getConcertById
* getAllConcertsByUserId
*  createConcert
* getComment
* createComment
* getAllCommentsByConcertId

There should be some assignments in order to implement them:
* @begununal -> getConcertById and getAllConcertByUserId
* @ozturkihsan  -> getComment and getAllCommentsByConcertId
* Hilal Dönmez -> createConcert and createComment

As long as API implementation is over, these functions should be implemented immediately.  Thus, deadline is on 28/10/2017 at 23:59.

**Comment by ffguven** [comment]
Done.
