### ISSUE TITLE
Preparing a Milestone Report

### ISSUE THREAD

**Issue by thedorum** [bounswe/bounswe2017group9#96]
I started working on Milestone Report on the customer's request with @ozturkihsan @kahremane @mehmetakify

**Comment by thedorum** [comment]
Deadline for Milestone Report is 02.11.2017 11:00 a.m.

**Comment by kahremane** [comment]
I am working on the summary part and I will send that part to @thedorum  until tomorrow 21:00.

**Comment by ozturkihsan** [comment]
I am working on 'List and status of deliverables' and 'evaluation of the status of deliverables and its impact on plan' part of the report and it will be sent until 1/11/2017 18:00.

**Comment by mehmetakify** [comment]
I working on the part of the milestone report of requirements, design and project plan

**Comment by mehmetakify** [comment]
I finished my milestone part.

**Comment by ffguven** [comment]
I'm gonna revise the milestone report after Doğa merged all the report.

**Comment by thedorum** [comment]
I revised and merged all the report, @hilaldonmez  also changed some parts of the report. I sent to @ffguven for last check.
